# Generated by Django 4.2.8 on 2025-12-04 06:52

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PipelineExecution",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "execution_id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        help_text="UUID unico para agrupar todas las etapas de una ejecucion",
                    ),
                ),
                (
                    "stage_name",
                    models.CharField(
                        db_index=True,
                        help_text="Nombre de la etapa del pipeline",
                        max_length=100,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("running", "Running"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("skipped", "Skipped"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "duration_seconds",
                    models.IntegerField(
                        blank=True,
                        help_text="Duracion de la etapa en segundos",
                        null=True,
                    ),
                ),
                (
                    "cache_hit",
                    models.BooleanField(
                        default=False,
                        help_text="Indica si se uso cache (Redis/MySQL/Drive)",
                    ),
                ),
                (
                    "config_hash",
                    models.CharField(
                        blank=True,
                        help_text="Hash MD5 de la configuracion para invalidacion de cache",
                        max_length=32,
                        null=True,
                    ),
                ),
                (
                    "error_message",
                    models.TextField(
                        blank=True,
                        help_text="Mensaje de error si status='failed'",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "pipeline_executions",
                "ordering": ["-created_at", "stage_name"],
                "indexes": [
                    models.Index(
                        fields=["execution_id"], name="pipeline_ex_executi_d9d1e0_idx"
                    ),
                    models.Index(
                        fields=["stage_name"], name="pipeline_ex_stage_n_efa21c_idx"
                    ),
                    models.Index(
                        fields=["status"], name="pipeline_ex_status_dc870e_idx"
                    ),
                    models.Index(
                        fields=["-created_at"], name="pipeline_ex_created_082170_idx"
                    ),
                ],
            },
        ),
    ]
