[pytest]
DJANGO_SETTINGS_MODULE = config.settings.testing
python_files = test_*.py
python_classes = Test*
python_functions = test_*
addopts =
    --verbose
    --strict-markers
    --tb=short
    --cov=apps/documents/services
    --cov=apps.analysis.use_cases.generate_bow
    --cov=apps.analysis.use_cases.calculate_tfidf
    --cov=apps.analysis.use_cases.train_topic_models
    --cov=apps.analysis.use_cases.analyze_factors
    --cov=apps.pipeline.use_cases.execute_pipeline
    --cov=apps.users.views
    --cov=apps.users.serializers
    --cov=apps.data_preparation.views
    --cov=apps.bertopic.views
    --cov-report=term-missing
    --cov-report=html
    --cov-fail-under=40
    --disable-warnings
markers =
    unit: Unit tests
    integration: Integration tests
    slow: Slow tests
    cache: Cache related tests
