[pytest]
DJANGO_SETTINGS_MODULE = config.settings.testing
python_files = test_*.py
python_classes = Test*
python_functions = test_*
addopts =
    --verbose
    --strict-markers
    --tb=short
    --cov=apps/documents/services
    --cov=apps/analysis/use_cases/generate_bow.py
    --cov=apps/analysis/use_cases/calculate_tfidf.py
    --cov=apps/infrastructure/cache/triple_layer_cache.py
    --cov-report=term-missing
    --cov-report=html
    --cov-fail-under=80
    --disable-warnings
markers =
    unit: Unit tests
    integration: Integration tests
    slow: Slow tests
    cache: Cache related tests
