# Generated by Django 4.2.8 on 2026-01-01 04:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="google_drive_access_token",
            field=models.TextField(
                blank=True,
                help_text="Token de acceso encriptado para Google Drive API",
                null=True,
                verbose_name="Token de Acceso de Google Drive",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="google_drive_connected",
            field=models.BooleanField(
                default=False,
                help_text="Indica si el usuario ha conectado su cuenta de Google Drive",
                verbose_name="Conectado a Google Drive",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="google_drive_connected_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Fecha y hora en que se conectó la cuenta de Google Drive",
                null=True,
                verbose_name="Fecha de Conexión a Google Drive",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="google_drive_email",
            field=models.EmailField(
                blank=True,
                help_text="Email de la cuenta de Google Drive conectada",
                max_length=254,
                null=True,
                verbose_name="Email de Google Drive",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="google_drive_refresh_token",
            field=models.TextField(
                blank=True,
                help_text="Token de refresco encriptado para renovar el access token",
                null=True,
                verbose_name="Token de Refresco de Google Drive",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="google_drive_scopes",
            field=models.TextField(
                blank=True,
                help_text="Permisos otorgados (JSON array)",
                null=True,
                verbose_name="Scopes de Google Drive",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="google_drive_token_expires_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Fecha y hora de expiración del access token",
                null=True,
                verbose_name="Expiración del Token",
            ),
        ),
    ]
