# Generated by Django 4.2.8 on 2026-01-01 05:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_add_google_drive_oauth"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="google_drive_oauth_state",
            field=models.CharField(
                blank=True,
                help_text="Parámetro state temporal para protección CSRF en OAuth (se limpia después de usar)",
                max_length=64,
                null=True,
                verbose_name="OAuth State Temporal",
            ),
        ),
    ]
