# Generated by Django 4.2.8 on 2026-09-12 22:10

import apps.users.models
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_add_oauth_state_field"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="user",
            managers=[
                ("objects", apps.users.models.CustomUserManager()),
            ],
        ),
    ]
