# Generated by Django 4.2.8 on 2026-01-02 17:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("datasets", "0002_datasetfile_directory_name_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DataPreparation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Nombre descriptivo para esta preparación",
                        max_length=255,
                        verbose_name="Nombre",
                    ),
                ),
                (
                    "custom_stopwords",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Lista de palabras a eliminar además de las por defecto",
                        verbose_name="Stopwords Personalizadas",
                    ),
                ),
                (
                    "filter_by_predominant_language",
                    models.BooleanField(
                        default=True,
                        help_text="Mantener solo archivos del idioma más común",
                        verbose_name="Filtrar por Idioma Predominante",
                    ),
                ),
                (
                    "enable_tokenization",
                    models.BooleanField(default=True, verbose_name="Tokenización"),
                ),
                (
                    "enable_lemmatization",
                    models.BooleanField(
                        default=True, verbose_name="Lematización (spaCy)"
                    ),
                ),
                (
                    "enable_special_chars_removal",
                    models.BooleanField(
                        default=True,
                        verbose_name="Eliminación de Caracteres Especiales",
                    ),
                ),
                (
                    "enable_integrity_check",
                    models.BooleanField(
                        default=True, verbose_name="Verificación de Integridad"
                    ),
                ),
                (
                    "enable_duplicate_removal",
                    models.BooleanField(
                        default=True, verbose_name="Eliminación de Duplicados"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pendiente"),
                            ("processing", "En Proceso"),
                            ("completed", "Completado"),
                            ("error", "Error"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="Estado",
                    ),
                ),
                (
                    "current_stage",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("extracting", "Extrayendo PDF"),
                            ("detecting_language", "Detectando Idiomas"),
                            ("cleaning", "Limpiando Texto"),
                            ("transforming", "Transformando"),
                            ("validating", "Validando"),
                            ("completed", "Completado"),
                        ],
                        max_length=30,
                        null=True,
                        verbose_name="Etapa Actual",
                    ),
                ),
                (
                    "progress_percentage",
                    models.IntegerField(
                        default=0,
                        help_text="Porcentaje de completitud (0-100)",
                        verbose_name="Progreso (%)",
                    ),
                ),
                (
                    "error_message",
                    models.TextField(
                        blank=True, null=True, verbose_name="Mensaje de Error"
                    ),
                ),
                (
                    "detected_languages",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text='Formato: {"en": 256, "es": 18, "ru": 13}',
                        verbose_name="Idiomas Detectados",
                    ),
                ),
                (
                    "predominant_language",
                    models.CharField(
                        blank=True,
                        help_text='Código ISO del idioma predominante (ej: "en", "es")',
                        max_length=10,
                        null=True,
                        verbose_name="Idioma Predominante",
                    ),
                ),
                (
                    "predominant_language_percentage",
                    models.FloatField(
                        default=0.0, verbose_name="Porcentaje del Idioma Predominante"
                    ),
                ),
                (
                    "total_files_analyzed",
                    models.IntegerField(
                        default=0, verbose_name="Total de Archivos Analizados"
                    ),
                ),
                (
                    "files_processed",
                    models.IntegerField(
                        default=0,
                        help_text="Archivos del idioma predominante",
                        verbose_name="Archivos Procesados",
                    ),
                ),
                (
                    "files_omitted",
                    models.IntegerField(
                        default=0,
                        help_text="Archivos de otros idiomas",
                        verbose_name="Archivos Omitidos",
                    ),
                ),
                (
                    "duplicates_removed",
                    models.IntegerField(
                        default=0, verbose_name="Duplicados Eliminados"
                    ),
                ),
                (
                    "processed_file_ids",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Lista de IDs de DatasetFile procesados",
                        verbose_name="IDs de Archivos Procesados",
                    ),
                ),
                (
                    "omitted_file_ids",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Lista de IDs de DatasetFile omitidos",
                        verbose_name="IDs de Archivos Omitidos",
                    ),
                ),
                (
                    "task_id",
                    models.CharField(
                        blank=True,
                        help_text="ID de la tarea de Celery para seguimiento",
                        max_length=255,
                        null=True,
                        verbose_name="Task ID (Celery)",
                    ),
                ),
                (
                    "processing_started_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Inicio de Procesamiento"
                    ),
                ),
                (
                    "processing_completed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Fin de Procesamiento"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de Creación"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Última Actualización"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="data_preparations",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Creado por",
                    ),
                ),
                (
                    "dataset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="preparations",
                        to="datasets.dataset",
                        verbose_name="Dataset",
                    ),
                ),
            ],
            options={
                "verbose_name": "Preparación de Datos",
                "verbose_name_plural": "Preparaciones de Datos",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["-created_at"], name="data_prepar_created_b84615_idx"
                    ),
                    models.Index(
                        fields=["status"], name="data_prepar_status_16d9a2_idx"
                    ),
                    models.Index(
                        fields=["dataset"], name="data_prepar_dataset_5ff286_idx"
                    ),
                ],
            },
        ),
    ]
