# Generated by Django 4.2.16 on 2026-03-20 00:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("datasets", "0005_fix_bow_tfidf_fk_to_datasetfile"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AIAnalysisConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "provider",
                    models.CharField(
                        choices=[
                            ("claude", "Claude (Anthropic)"),
                            ("gemini", "Gemini (Google)"),
                            ("openai", "OpenAI (ChatGPT)"),
                        ],
                        max_length=20,
                        verbose_name="Proveedor",
                    ),
                ),
                (
                    "model_name",
                    models.CharField(
                        help_text="Modelo especifico (ej: claude-sonnet-4-6, gemini-1.5-pro, gpt-4o)",
                        max_length=100,
                        verbose_name="Nombre del modelo",
                    ),
                ),
                (
                    "prompt_template",
                    models.TextField(verbose_name="Plantilla de prompt"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pendiente"),
                            ("processing", "Procesando"),
                            ("completed", "Completado"),
                            ("error", "Error"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="Estado",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ai_analysis_configs",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Creado por",
                    ),
                ),
                (
                    "dataset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ai_analysis_configs",
                        to="datasets.dataset",
                        verbose_name="Dataset",
                    ),
                ),
            ],
            options={
                "db_table": "ai_analysis_configs",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="AIAnalysisResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "provider",
                    models.CharField(
                        choices=[
                            ("claude", "Claude (Anthropic)"),
                            ("gemini", "Gemini (Google)"),
                            ("openai", "OpenAI (ChatGPT)"),
                        ],
                        max_length=20,
                        verbose_name="Proveedor",
                    ),
                ),
                ("raw_response", models.TextField(verbose_name="Respuesta cruda")),
                (
                    "success_cases",
                    models.JSONField(
                        default=list,
                        help_text="Lista de casos de exito de transformacion digital en IES",
                        verbose_name="Casos de exito identificados",
                    ),
                ),
                (
                    "identified_factors",
                    models.JSONField(
                        default=list,
                        help_text="Factores de transformacion digital encontrados por el LLM",
                        verbose_name="Factores identificados",
                    ),
                ),
                (
                    "factor_comparison",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Comparacion de factores IA vs analisis NLP tradicional",
                        verbose_name="Comparacion con NLP tradicional",
                    ),
                ),
                (
                    "tokens_used",
                    models.IntegerField(default=0, verbose_name="Tokens utilizados"),
                ),
                (
                    "processing_time_seconds",
                    models.FloatField(
                        default=0.0, verbose_name="Tiempo de procesamiento (s)"
                    ),
                ),
                (
                    "error_message",
                    models.TextField(
                        blank=True, null=True, verbose_name="Mensaje de error"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "config",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="results",
                        to="ai_analysis.aianalysisconfig",
                        verbose_name="Configuracion",
                    ),
                ),
            ],
            options={
                "db_table": "ai_analysis_results",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="AIComparisonResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "consensus_factors",
                    models.JSONField(
                        default=list,
                        help_text="Factores en los que todos los proveedores coinciden",
                        verbose_name="Factores en consenso",
                    ),
                ),
                (
                    "divergent_factors",
                    models.JSONField(
                        default=list,
                        help_text="Factores donde los proveedores difieren",
                        verbose_name="Factores divergentes",
                    ),
                ),
                (
                    "nlp_agreement",
                    models.JSONField(
                        default=dict,
                        help_text="Nivel de acuerdo entre analisis IA y NLP tradicional",
                        verbose_name="Acuerdo con NLP tradicional",
                    ),
                ),
                (
                    "comparison_summary",
                    models.TextField(
                        blank=True, default="", verbose_name="Resumen de comparacion"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "claude_result",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="ai_analysis.aianalysisresult",
                        verbose_name="Resultado Claude",
                    ),
                ),
                (
                    "config",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comparison",
                        to="ai_analysis.aianalysisconfig",
                        verbose_name="Configuracion",
                    ),
                ),
                (
                    "gemini_result",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="ai_analysis.aianalysisresult",
                        verbose_name="Resultado Gemini",
                    ),
                ),
                (
                    "openai_result",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="ai_analysis.aianalysisresult",
                        verbose_name="Resultado OpenAI",
                    ),
                ),
            ],
            options={
                "db_table": "ai_comparison_results",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="aianalysisresult",
            index=models.Index(
                fields=["provider"], name="ai_analysis_provide_0d5728_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="aianalysisresult",
            index=models.Index(
                fields=["config", "provider"], name="ai_analysis_config__2668e1_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="aianalysisconfig",
            index=models.Index(fields=["status"], name="ai_analysis_status_be7ad2_idx"),
        ),
        migrations.AddIndex(
            model_name="aianalysisconfig",
            index=models.Index(
                fields=["provider"], name="ai_analysis_provide_e012b0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="aianalysisconfig",
            index=models.Index(
                fields=["-created_at"], name="ai_analysis_created_fdb2d4_idx"
            ),
        ),
    ]
