# Generated by Django 4.2.8 on 2026-01-06 20:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("data_preparation", "0001_initial"),
        ("datasets", "0002_datasetfile_directory_name_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="NerAnalysis",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Nombre descriptivo del análisis NER", max_length=200
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Descripción opcional del análisis",
                        null=True,
                    ),
                ),
                (
                    "source_type",
                    models.CharField(
                        choices=[
                            ("data_preparation", "Preparación de Datos (Preprocesado)"),
                            ("dataset", "Dataset Directo (Textos Raw)"),
                        ],
                        default="data_preparation",
                        help_text="Tipo de fuente de datos",
                        max_length=20,
                    ),
                ),
                (
                    "spacy_model",
                    models.CharField(
                        choices=[
                            ("en_core_web_sm", "Inglés (Pequeño) - en_core_web_sm"),
                            ("en_core_web_md", "Inglés (Mediano) - en_core_web_md"),
                            ("en_core_web_lg", "Inglés (Grande) - en_core_web_lg"),
                            ("es_core_news_sm", "Español (Pequeño) - es_core_news_sm"),
                            ("es_core_news_md", "Español (Mediano) - es_core_news_md"),
                            ("es_core_news_lg", "Español (Grande) - es_core_news_lg"),
                        ],
                        default="en_core_web_sm",
                        help_text="Modelo de spaCy a utilizar",
                        max_length=50,
                    ),
                ),
                (
                    "selected_entities",
                    models.JSONField(
                        default=list, help_text="Lista de tipos de entidades a extraer"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pendiente"),
                            ("processing", "Procesando"),
                            ("completed", "Completado"),
                            ("error", "Error"),
                        ],
                        default="pending",
                        help_text="Estado actual del análisis",
                        max_length=20,
                    ),
                ),
                (
                    "current_stage",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("pending", "Pendiente"),
                            ("loading_model", "Cargando modelo spaCy"),
                            ("loading_data", "Cargando datos"),
                            ("extracting_entities", "Extrayendo entidades"),
                            ("calculating_stats", "Calculando estadísticas"),
                            ("analyzing_cooccurrences", "Analizando co-ocurrencias"),
                            ("saving_results", "Guardando resultados"),
                            ("completed", "Completado"),
                        ],
                        default="pending",
                        help_text="Etapa actual del procesamiento",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "progress_percentage",
                    models.IntegerField(
                        default=0, help_text="Porcentaje de progreso (0-100)"
                    ),
                ),
                (
                    "error_message",
                    models.TextField(
                        blank=True,
                        help_text="Mensaje de error si el procesamiento falla",
                        null=True,
                    ),
                ),
                (
                    "documents_processed",
                    models.IntegerField(
                        default=0, help_text="Número de documentos procesados"
                    ),
                ),
                (
                    "total_entities_found",
                    models.IntegerField(
                        default=0, help_text="Total de entidades encontradas"
                    ),
                ),
                (
                    "unique_entities_count",
                    models.IntegerField(
                        default=0, help_text="Número de entidades únicas"
                    ),
                ),
                (
                    "entity_types_found",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Conteo por tipo de entidad. Ej: {'PERSON': 150, 'ORG': 80}",
                    ),
                ),
                (
                    "entities",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Lista completa de entidades con frecuencias y documentos",
                    ),
                ),
                (
                    "top_entities_by_type",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Top N entidades por cada categoría",
                    ),
                ),
                (
                    "cooccurrences",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Análisis de entidades que co-ocurren en mismos documentos",
                    ),
                ),
                (
                    "entity_distribution",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Distribución porcentual de tipos de entidades",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="Fecha de creación"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="Fecha de última actualización"
                    ),
                ),
                (
                    "processing_started_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Fecha de inicio del procesamiento",
                        null=True,
                    ),
                ),
                (
                    "processing_completed_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Fecha de finalización del procesamiento",
                        null=True,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        help_text="Usuario que creó este análisis",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ner_analyses",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "data_preparation",
                    models.ForeignKey(
                        blank=True,
                        help_text="Preparación de datos a utilizar (si source_type='data_preparation')",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ner_analyses",
                        to="data_preparation.datapreparation",
                    ),
                ),
                (
                    "dataset",
                    models.ForeignKey(
                        blank=True,
                        help_text="Dataset directo a utilizar (si source_type='dataset')",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ner_analyses",
                        to="datasets.dataset",
                    ),
                ),
            ],
            options={
                "verbose_name": "Análisis NER",
                "verbose_name_plural": "Análisis NER",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["created_by", "-created_at"],
                        name="ner_analysi_created_099f8a_idx",
                    ),
                    models.Index(
                        fields=["source_type"], name="ner_analysi_source__99ac53_idx"
                    ),
                    models.Index(
                        fields=["status"], name="ner_analysi_status_757388_idx"
                    ),
                    models.Index(
                        fields=["spacy_model"], name="ner_analysi_spacy_m_dc9aae_idx"
                    ),
                ],
            },
        ),
    ]
