# Generated by Django 4.2.8 on 2026-01-07 00:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ner_analysis", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="neranalysis",
            name="spacy_model",
            field=models.CharField(
                choices=[
                    ("en_core_web_sm", "Inglés (Pequeño) - en_core_web_sm"),
                    ("en_core_web_md", "Inglés (Mediano) - en_core_web_md"),
                    ("en_core_web_lg", "Inglés (Grande) - en_core_web_lg"),
                    ("en_core_web_trf", "Inglés (Alta Precisión) - en_core_web_trf"),
                    ("es_core_news_sm", "Español (Pequeño) - es_core_news_sm"),
                    ("es_core_news_md", "Español (Mediano) - es_core_news_md"),
                    ("es_core_news_lg", "Español (Grande) - es_core_news_lg"),
                ],
                default="en_core_web_sm",
                help_text="Modelo de spaCy a utilizar",
                max_length=50,
            ),
        ),
    ]
