# Generated by Django 4.2.8 on 2026-01-08 15:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("datasets", "0002_datasetfile_directory_name_and_more"),
        ("data_preparation", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="BERTopicAnalysis",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Nombre")),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Descripción"),
                ),
                (
                    "source_type",
                    models.CharField(
                        choices=[
                            ("data_preparation", "Data Preparation"),
                            ("dataset", "Dataset"),
                        ],
                        max_length=50,
                        verbose_name="Tipo de fuente",
                    ),
                ),
                (
                    "embedding_model",
                    models.CharField(
                        choices=[
                            ("all-MiniLM-L6-v2", "MiniLM-L6-v2 (Rápido, Inglés)"),
                            ("all-mpnet-base-v2", "MPNet (Mejor calidad, Inglés)"),
                            (
                                "paraphrase-multilingual-MiniLM-L12-v2",
                                "Multilingual (Español/Inglés)",
                            ),
                        ],
                        default="all-MiniLM-L6-v2",
                        max_length=100,
                        verbose_name="Modelo de embeddings",
                    ),
                ),
                (
                    "n_neighbors",
                    models.IntegerField(default=15, verbose_name="N Neighbors (UMAP)"),
                ),
                (
                    "n_components",
                    models.IntegerField(default=5, verbose_name="N Components (UMAP)"),
                ),
                (
                    "min_cluster_size",
                    models.IntegerField(
                        default=10, verbose_name="Min Cluster Size (HDBSCAN)"
                    ),
                ),
                (
                    "min_samples",
                    models.IntegerField(
                        default=5, verbose_name="Min Samples (HDBSCAN)"
                    ),
                ),
                (
                    "nr_topics",
                    models.IntegerField(
                        blank=True,
                        null=True,
                        verbose_name="Número de tópicos (auto si es null)",
                    ),
                ),
                (
                    "num_words",
                    models.IntegerField(default=10, verbose_name="Palabras por tópico"),
                ),
                (
                    "random_seed",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Semilla aleatoria"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pendiente"),
                            ("processing", "Procesando"),
                            ("completed", "Completado"),
                            ("error", "Error"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="Estado",
                    ),
                ),
                (
                    "current_stage",
                    models.CharField(
                        choices=[
                            ("pending", "Pendiente"),
                            ("loading_data", "Cargando datos"),
                            ("loading_model", "Cargando modelo BERT"),
                            ("generating_embeddings", "Generando embeddings"),
                            (
                                "reducing_dimensions",
                                "Reduciendo dimensionalidad (UMAP)",
                            ),
                            ("clustering", "Clustering (HDBSCAN)"),
                            ("extracting_topics", "Extrayendo tópicos"),
                            ("calculating_coherence", "Calculando coherencia"),
                            ("saving_results", "Guardando resultados"),
                            ("completed", "Completado"),
                        ],
                        default="pending",
                        max_length=50,
                        verbose_name="Etapa actual",
                    ),
                ),
                (
                    "progress_percentage",
                    models.IntegerField(default=0, verbose_name="Progreso (%)"),
                ),
                (
                    "error_message",
                    models.TextField(
                        blank=True, null=True, verbose_name="Mensaje de error"
                    ),
                ),
                (
                    "documents_processed",
                    models.IntegerField(
                        default=0, verbose_name="Documentos procesados"
                    ),
                ),
                (
                    "vocabulary_size",
                    models.IntegerField(
                        default=0, verbose_name="Tamaño del vocabulario"
                    ),
                ),
                (
                    "num_topics_found",
                    models.IntegerField(
                        default=0, verbose_name="Número de tópicos encontrados"
                    ),
                ),
                (
                    "coherence_score",
                    models.FloatField(
                        blank=True, null=True, verbose_name="Coherencia (C_V)"
                    ),
                ),
                (
                    "num_outliers",
                    models.IntegerField(
                        default=0, verbose_name="Documentos outliers (tópico -1)"
                    ),
                ),
                (
                    "topics",
                    models.JSONField(
                        default=list,
                        help_text="Lista de tópicos con palabras y pesos",
                        verbose_name="Tópicos extraídos",
                    ),
                ),
                (
                    "document_topics",
                    models.JSONField(
                        default=list,
                        help_text="Asignación de documentos a tópicos",
                        verbose_name="Documentos por tópico",
                    ),
                ),
                (
                    "topic_distribution",
                    models.JSONField(
                        default=list,
                        help_text="Cantidad de documentos por tópico",
                        verbose_name="Distribución de tópicos",
                    ),
                ),
                (
                    "topic_sizes",
                    models.JSONField(
                        default=dict,
                        help_text="Número de documentos por tópico (incluyendo outliers)",
                        verbose_name="Tamaños de tópicos",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Creado"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Actualizado"),
                ),
                (
                    "processing_started_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Inicio de procesamiento"
                    ),
                ),
                (
                    "processing_completed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Fin de procesamiento"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bertopic_analyses",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Creado por",
                    ),
                ),
                (
                    "data_preparation",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bertopic_analyses",
                        to="data_preparation.datapreparation",
                        verbose_name="Preparación de datos",
                    ),
                ),
                (
                    "dataset",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bertopic_analyses",
                        to="datasets.dataset",
                        verbose_name="Dataset",
                    ),
                ),
            ],
            options={
                "verbose_name": "Análisis BERTopic",
                "verbose_name_plural": "Análisis BERTopic",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["created_by", "-created_at"],
                        name="bertopic_be_created_3ee994_idx",
                    ),
                    models.Index(
                        fields=["status"], name="bertopic_be_status_349804_idx"
                    ),
                ],
            },
        ),
    ]
