# Generated by Django 4.2.8 on 2026-01-04 16:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("data_preparation", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="NgramAnalysis",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=255, verbose_name="Nombre del análisis"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Descripción"),
                ),
                (
                    "ngram_configurations",
                    models.JSONField(
                        default=list, verbose_name="Configuraciones de N-gramas"
                    ),
                ),
                (
                    "max_features",
                    models.IntegerField(
                        default=100000, verbose_name="Máximo de features"
                    ),
                ),
                (
                    "min_df",
                    models.IntegerField(
                        default=1, verbose_name="Frecuencia mínima de documento"
                    ),
                ),
                (
                    "max_df",
                    models.FloatField(
                        default=1.0, verbose_name="Frecuencia máxima de documento"
                    ),
                ),
                (
                    "document_count",
                    models.IntegerField(default=0, verbose_name="Número de documentos"),
                ),
                (
                    "total_configurations",
                    models.IntegerField(
                        default=0, verbose_name="Total de configuraciones"
                    ),
                ),
                (
                    "results",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        verbose_name="Resultados por configuración",
                    ),
                ),
                (
                    "comparisons",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        verbose_name="Comparaciones entre configuraciones",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pendiente"),
                            ("processing", "Procesando"),
                            ("completed", "Completado"),
                            ("error", "Error"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="Estado",
                    ),
                ),
                (
                    "current_stage",
                    models.CharField(
                        choices=[
                            ("pending", "Pendiente"),
                            ("loading_data", "Cargando datos"),
                            ("processing_ngrams", "Procesando N-gramas"),
                            ("calculating_comparisons", "Calculando comparaciones"),
                            ("saving_results", "Guardando resultados"),
                            ("completed", "Completado"),
                        ],
                        default="pending",
                        max_length=50,
                        verbose_name="Etapa actual",
                    ),
                ),
                (
                    "progress_percentage",
                    models.IntegerField(
                        default=0, verbose_name="Porcentaje de progreso"
                    ),
                ),
                (
                    "error_message",
                    models.TextField(blank=True, verbose_name="Mensaje de error"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de creación"
                    ),
                ),
                (
                    "processing_started_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Inicio de procesamiento"
                    ),
                ),
                (
                    "processing_completed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Fin de procesamiento"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Última actualización"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ngram_analyses",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Creado por",
                    ),
                ),
                (
                    "data_preparation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ngram_analyses",
                        to="data_preparation.datapreparation",
                        verbose_name="Preparación de datos",
                    ),
                ),
            ],
            options={
                "verbose_name": "Análisis de N-gramas",
                "verbose_name_plural": "Análisis de N-gramas",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["-created_at"], name="ngram_analy_created_31bd8a_idx"
                    ),
                    models.Index(
                        fields=["status"], name="ngram_analy_status_bc9f0f_idx"
                    ),
                    models.Index(
                        fields=["data_preparation"],
                        name="ngram_analy_data_pr_074d79_idx",
                    ),
                ],
            },
        ),
    ]
