# Generated by Django 4.2.8 on 2026-01-05 16:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("bag_of_words", "0002_remove_tfidf_fields"),
        ("data_preparation", "0001_initial"),
        ("ngram_analysis", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TfIdfAnalysis",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=255, verbose_name="Nombre del análisis"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Descripción"),
                ),
                (
                    "source_type",
                    models.CharField(
                        choices=[
                            ("data_preparation", "Preparación de Datos"),
                            ("bag_of_words", "Bolsa de Palabras"),
                            ("ngram_config", "Configuración N-grama específica"),
                            ("ngram_all", "Todas las configuraciones N-grama"),
                            ("ngram_vocabulary", "Vocabulario completo N-grama"),
                        ],
                        max_length=50,
                        verbose_name="Tipo de origen",
                    ),
                ),
                (
                    "ngram_config",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="Configuración N-grama"
                    ),
                ),
                (
                    "max_features",
                    models.IntegerField(
                        default=100000, verbose_name="Máximo de features"
                    ),
                ),
                (
                    "min_df",
                    models.IntegerField(
                        default=1, verbose_name="Frecuencia mínima de documento"
                    ),
                ),
                (
                    "max_df",
                    models.FloatField(
                        default=1.0, verbose_name="Frecuencia máxima de documento"
                    ),
                ),
                (
                    "ngram_min",
                    models.IntegerField(default=1, verbose_name="N-grama mínimo"),
                ),
                (
                    "ngram_max",
                    models.IntegerField(default=1, verbose_name="N-grama máximo"),
                ),
                ("use_idf", models.BooleanField(default=True, verbose_name="Usar IDF")),
                (
                    "smooth_idf",
                    models.BooleanField(default=True, verbose_name="Suavizar IDF"),
                ),
                (
                    "sublinear_tf",
                    models.BooleanField(default=False, verbose_name="TF sublineal"),
                ),
                (
                    "document_count",
                    models.IntegerField(default=0, verbose_name="Número de documentos"),
                ),
                (
                    "vocabulary_size",
                    models.IntegerField(
                        default=0, verbose_name="Tamaño del vocabulario"
                    ),
                ),
                (
                    "tf_matrix",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="Matriz TF"
                    ),
                ),
                (
                    "idf_vector",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="Vector IDF"
                    ),
                ),
                (
                    "tfidf_matrix",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="Matriz TF-IDF"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pendiente"),
                            ("processing", "Procesando"),
                            ("completed", "Completado"),
                            ("error", "Error"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="Estado",
                    ),
                ),
                (
                    "current_stage",
                    models.CharField(
                        choices=[
                            ("pending", "Pendiente"),
                            ("loading_data", "Cargando datos"),
                            ("calculating_tf", "Calculando matriz TF"),
                            ("calculating_idf", "Calculando vector IDF"),
                            ("calculating_tfidf", "Calculando matriz TF-IDF"),
                            ("saving_results", "Guardando resultados"),
                            ("completed", "Completado"),
                        ],
                        default="pending",
                        max_length=50,
                        verbose_name="Etapa actual",
                    ),
                ),
                (
                    "progress_percentage",
                    models.IntegerField(
                        default=0, verbose_name="Porcentaje de progreso"
                    ),
                ),
                (
                    "error_message",
                    models.TextField(blank=True, verbose_name="Mensaje de error"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de creación"
                    ),
                ),
                (
                    "processing_started_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Inicio de procesamiento"
                    ),
                ),
                (
                    "processing_completed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Fin de procesamiento"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Última actualización"
                    ),
                ),
                (
                    "bag_of_words",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tfidf_analyses",
                        to="bag_of_words.bagofwords",
                        verbose_name="Bolsa de Palabras",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tfidf_analyses",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Creado por",
                    ),
                ),
                (
                    "data_preparation",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tfidf_analyses",
                        to="data_preparation.datapreparation",
                        verbose_name="Preparación de datos",
                    ),
                ),
                (
                    "ngram_analysis",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tfidf_analyses",
                        to="ngram_analysis.ngramanalysis",
                        verbose_name="Análisis de N-gramas",
                    ),
                ),
            ],
            options={
                "verbose_name": "Análisis TF-IDF",
                "verbose_name_plural": "Análisis TF-IDF",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["-created_at"], name="tfidf_analy_created_87725c_idx"
                    ),
                    models.Index(
                        fields=["status"], name="tfidf_analy_status_c651cb_idx"
                    ),
                    models.Index(
                        fields=["source_type"], name="tfidf_analy_source__ab7bae_idx"
                    ),
                ],
            },
        ),
    ]
