# Generated by Django 6.0.3 on 2026-03-26 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tfidf_analysis', '0003_add_vectorizer_artifact'),
    ]

    operations = [
        migrations.AddField(
            model_name='tfidfanalysis',
            name='vectorizer_artifact_bin',
            field=models.BinaryField(blank=True, help_text='TfidfVectorizer serializado (joblib) almacenado en DB para persistencia en hosting efímero', null=True, verbose_name='Artefacto del vectorizador (DB)'),
        ),
    ]
