# Generated by Django 4.2.8 on 2025-12-04 06:52

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Document",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("drive_file_id", models.CharField(max_length=255, unique=True)),
                ("filename", models.CharField(max_length=500)),
                (
                    "language_code",
                    models.CharField(blank=True, max_length=5, null=True),
                ),
                ("language_confidence", models.FloatField(blank=True, null=True)),
                ("txt_content", models.TextField(blank=True, null=True)),
                ("preprocessed_text", models.TextField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("error", "Error"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "documents",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["status"], name="documents_status_f31a08_idx"),
                    models.Index(
                        fields=["language_code"], name="documents_languag_43abac_idx"
                    ),
                ],
            },
        ),
    ]
