# Generated by Django 4.2.8 on 2025-12-04 06:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("documents", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Vocabulary",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("term", models.CharField(db_index=True, max_length=255, unique=True)),
                ("global_frequency", models.IntegerField(default=0)),
                ("document_frequency", models.IntegerField(default=0)),
                ("idf_score", models.FloatField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "vocabulary",
                "ordering": ["-global_frequency"],
                "indexes": [
                    models.Index(
                        fields=["-global_frequency"],
                        name="vocabulary_global__3c3dd7_idx",
                    ),
                    models.Index(fields=["term"], name="vocabulary_term_eac029_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="Topic",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "model_type",
                    models.CharField(
                        choices=[
                            ("lda", "LDA (Latent Dirichlet Allocation)"),
                            ("nmf", "NMF (Non-negative Matrix Factorization)"),
                            ("lsa", "LSA (Latent Semantic Analysis)"),
                            ("plsa", "pLSA (Probabilistic LSA)"),
                        ],
                        max_length=10,
                    ),
                ),
                ("topic_number", models.IntegerField()),
                (
                    "top_words",
                    models.JSONField(
                        help_text="Lista de palabras principales del tema con sus pesos"
                    ),
                ),
                ("coherence_score", models.FloatField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "topics",
                "ordering": ["model_type", "topic_number"],
                "indexes": [
                    models.Index(
                        fields=["model_type"], name="topics_model_t_659334_idx"
                    )
                ],
                "unique_together": {("model_type", "topic_number")},
            },
        ),
        migrations.CreateModel(
            name="MatrixStorage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "matrix_type",
                    models.CharField(
                        choices=[
                            ("bow", "Bag of Words"),
                            ("tfidf", "TF-IDF"),
                            ("pca", "PCA"),
                            ("tsne", "t-SNE"),
                            ("umap", "UMAP"),
                        ],
                        max_length=20,
                    ),
                ),
                ("drive_file_id", models.CharField(max_length=255)),
                ("shape_rows", models.IntegerField()),
                ("shape_cols", models.IntegerField()),
                ("sparsity", models.FloatField(blank=True, null=True)),
                ("file_size_bytes", models.BigIntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "matrix_storage",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["matrix_type"], name="matrix_stor_matrix__42872f_idx"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Factor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("tecnologico", "Tecnológico"),
                            ("organizacional", "Organizacional"),
                            ("humano", "Humano"),
                            ("estrategico", "Estratégico"),
                            ("financiero", "Financiero"),
                            ("pedagogico", "Pedagógico"),
                            ("infraestructura", "Infraestructura"),
                            ("seguridad", "Seguridad"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "keywords",
                    models.JSONField(
                        help_text="Lista de palabras clave asociadas a este factor"
                    ),
                ),
                ("global_frequency", models.IntegerField(default=0)),
                ("relevance_score", models.FloatField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "factors",
                "ordering": ["-relevance_score", "category"],
                "indexes": [
                    models.Index(
                        fields=["category"], name="factors_categor_4489f5_idx"
                    ),
                    models.Index(
                        fields=["-relevance_score"], name="factors_relevan_a4c859_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="TfidfMatrix",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tfidf_score", models.FloatField()),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tfidf_entries",
                        to="documents.document",
                    ),
                ),
                (
                    "term",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tfidf_entries",
                        to="analysis.vocabulary",
                    ),
                ),
            ],
            options={
                "db_table": "tfidf_matrix",
                "indexes": [
                    models.Index(
                        fields=["-tfidf_score"], name="tfidf_matri_tfidf_s_8cdece_idx"
                    ),
                    models.Index(
                        fields=["document", "term"],
                        name="tfidf_matri_documen_5f617d_idx",
                    ),
                ],
                "unique_together": {("document", "term")},
            },
        ),
        migrations.CreateModel(
            name="DocumentTopic",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "probability",
                    models.FloatField(
                        help_text="Probabilidad de que el documento pertenezca a este tema (0-1)"
                    ),
                ),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="topic_assignments",
                        to="documents.document",
                    ),
                ),
                (
                    "topic",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="document_assignments",
                        to="analysis.topic",
                    ),
                ),
            ],
            options={
                "db_table": "document_topics",
                "ordering": ["-probability"],
                "indexes": [
                    models.Index(
                        fields=["-probability"], name="document_to_probabi_fd4d33_idx"
                    ),
                    models.Index(
                        fields=["document", "topic"],
                        name="document_to_documen_2d664b_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="DocumentFactor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("mention_count", models.IntegerField(default=0)),
                (
                    "relevance_score",
                    models.FloatField(
                        blank=True,
                        help_text="Score de relevancia normalizado",
                        null=True,
                    ),
                ),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="factor_mentions",
                        to="documents.document",
                    ),
                ),
                (
                    "factor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="document_mentions",
                        to="analysis.factor",
                    ),
                ),
            ],
            options={
                "db_table": "document_factors",
                "ordering": ["-relevance_score"],
                "indexes": [
                    models.Index(
                        fields=["-relevance_score"],
                        name="document_fa_relevan_8fb7a2_idx",
                    ),
                    models.Index(
                        fields=["document", "factor"],
                        name="document_fa_documen_89efb0_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="BowMatrix",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("frequency", models.IntegerField(default=0)),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bow_entries",
                        to="documents.document",
                    ),
                ),
                (
                    "term",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bow_entries",
                        to="analysis.vocabulary",
                    ),
                ),
            ],
            options={
                "db_table": "bow_matrix",
                "indexes": [
                    models.Index(
                        fields=["-frequency"], name="bow_matrix_frequen_bff346_idx"
                    ),
                    models.Index(
                        fields=["document", "term"],
                        name="bow_matrix_documen_fa0d06_idx",
                    ),
                ],
                "unique_together": {("document", "term")},
            },
        ),
    ]
