# Generated by Django 4.2.8 on 2026-03-15 16:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("data_preparation", "0001_initial"),
        ("analysis", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="FactorAnalysisRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Nombre")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pendiente"),
                            ("running", "Ejecutando"),
                            ("completed", "Completado"),
                            ("error", "Error"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="Estado",
                    ),
                ),
                ("document_count", models.IntegerField(default=0)),
                ("factor_count", models.IntegerField(default=0)),
                (
                    "results",
                    models.JSONField(
                        blank=True,
                        help_text="Resultados completos del análisis",
                        null=True,
                    ),
                ),
                ("error_message", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "data_preparation",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="factor_runs",
                        to="data_preparation.datapreparation",
                        verbose_name="Preparación de datos",
                    ),
                ),
            ],
            options={
                "db_table": "factor_analysis_runs",
                "ordering": ["-created_at"],
            },
        ),
    ]
