# Generated by Django 4.2.8 on 2026-03-15 20:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("datasets", "0005_fix_bow_tfidf_fk_to_datasetfile"),
        ("analysis", "0002_add_factor_analysis_run"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bowmatrix",
            name="document",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bow_entries",
                to="datasets.datasetfile",
            ),
        ),
        migrations.AlterField(
            model_name="tfidfmatrix",
            name="document",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tfidf_entries",
                to="datasets.datasetfile",
            ),
        ),
    ]
