# Generated by Django 4.2.16 on 2026-03-19 22:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("datasets", "0005_fix_bow_tfidf_fk_to_datasetfile"),
        ("analysis", "0003_fix_bow_tfidf_fk_to_datasetfile"),
    ]

    operations = [
        migrations.AlterField(
            model_name="documentfactor",
            name="document",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="factor_mentions",
                to="datasets.datasetfile",
            ),
        ),
        migrations.AlterField(
            model_name="documenttopic",
            name="document",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="topic_assignments",
                to="datasets.datasetfile",
            ),
        ),
    ]
