# Generated by Django 4.2.8 on 2026-01-07 22:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("data_preparation", "0001_initial"),
        ("datasets", "0002_datasetfile_directory_name_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="TopicModeling",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=255, verbose_name="Nombre del Análisis"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Descripción"),
                ),
                (
                    "source_type",
                    models.CharField(
                        choices=[
                            ("data_preparation", "Preparación de Datos (Preprocesado)"),
                            ("dataset", "Dataset Directo (Textos Raw)"),
                        ],
                        max_length=50,
                        verbose_name="Tipo de Fuente",
                    ),
                ),
                (
                    "algorithm",
                    models.CharField(
                        choices=[
                            ("lsa", "LSA (Latent Semantic Analysis)"),
                            ("nmf", "NMF (Non-negative Matrix Factorization)"),
                            ("plsa", "PLSA (Probabilistic Latent Semantic Analysis)"),
                            ("lda", "LDA (Latent Dirichlet Allocation)"),
                        ],
                        default="lda",
                        max_length=20,
                        verbose_name="Algoritmo",
                    ),
                ),
                (
                    "num_topics",
                    models.IntegerField(default=10, verbose_name="Número de Tópicos"),
                ),
                (
                    "num_words",
                    models.IntegerField(default=10, verbose_name="Palabras por Tópico"),
                ),
                (
                    "max_iterations",
                    models.IntegerField(
                        default=100, verbose_name="Iteraciones Máximas"
                    ),
                ),
                (
                    "random_seed",
                    models.IntegerField(
                        blank=True,
                        default=42,
                        null=True,
                        verbose_name="Semilla Aleatoria",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pendiente"),
                            ("processing", "Procesando"),
                            ("completed", "Completado"),
                            ("error", "Error"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="Estado",
                    ),
                ),
                (
                    "current_stage",
                    models.CharField(
                        choices=[
                            ("pending", "Pendiente"),
                            ("loading_data", "Cargando datos"),
                            ("preprocessing", "Preprocesando textos"),
                            ("vectorizing", "Vectorizando"),
                            ("training_model", "Entrenando modelo"),
                            ("extracting_topics", "Extrayendo tópicos"),
                            ("calculating_coherence", "Calculando coherencia"),
                            ("saving_results", "Guardando resultados"),
                            ("completed", "Completado"),
                        ],
                        default="pending",
                        max_length=50,
                        verbose_name="Etapa Actual",
                    ),
                ),
                (
                    "progress_percentage",
                    models.IntegerField(default=0, verbose_name="Progreso (%)"),
                ),
                (
                    "error_message",
                    models.TextField(
                        blank=True, null=True, verbose_name="Mensaje de Error"
                    ),
                ),
                (
                    "documents_processed",
                    models.IntegerField(
                        default=0, verbose_name="Documentos Procesados"
                    ),
                ),
                (
                    "vocabulary_size",
                    models.IntegerField(
                        default=0, verbose_name="Tamaño del Vocabulario"
                    ),
                ),
                (
                    "coherence_score",
                    models.FloatField(
                        blank=True, null=True, verbose_name="Score de Coherencia"
                    ),
                ),
                (
                    "perplexity_score",
                    models.FloatField(
                        blank=True, null=True, verbose_name="Score de Perplejidad"
                    ),
                ),
                (
                    "topics",
                    models.JSONField(default=list, verbose_name="Tópicos Extraídos"),
                ),
                (
                    "document_topics",
                    models.JSONField(
                        default=list, verbose_name="Documentos por Tópico"
                    ),
                ),
                (
                    "topic_distribution",
                    models.JSONField(
                        default=list, verbose_name="Distribución de Tópicos"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Creado"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Actualizado"),
                ),
                (
                    "processing_started_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Inicio de Procesamiento"
                    ),
                ),
                (
                    "processing_completed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Fin de Procesamiento"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="topic_modelings",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Creado por",
                    ),
                ),
                (
                    "data_preparation",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="topic_modelings",
                        to="data_preparation.datapreparation",
                        verbose_name="Preparación de Datos",
                    ),
                ),
                (
                    "dataset",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="topic_modelings",
                        to="datasets.dataset",
                        verbose_name="Dataset",
                    ),
                ),
            ],
            options={
                "verbose_name": "Topic Modeling",
                "verbose_name_plural": "Topic Modelings",
                "db_table": "topic_modeling",
                "ordering": ["-created_at"],
            },
        ),
    ]
