# Generated by Django 6.0.3 on 2026-03-26 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topic_modeling', '0002_add_model_artifacts'),
    ]

    operations = [
        migrations.AddField(
            model_name='topicmodeling',
            name='model_artifact_bin',
            field=models.BinaryField(blank=True, help_text='Modelo de tópicos serializado (joblib) almacenado en DB para persistencia', null=True, verbose_name='Artefacto del modelo (DB)'),
        ),
        migrations.AddField(
            model_name='topicmodeling',
            name='vectorizer_artifact_bin',
            field=models.BinaryField(blank=True, help_text='Vectorizador serializado (joblib) almacenado en DB para persistencia', null=True, verbose_name='Artefacto del vectorizador (DB)'),
        ),
    ]
