# Generated by Django 4.2.8 on 2026-09-13 18:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("topic_modeling", "0003_topicmodeling_model_artifact_bin_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="topicmodeling",
            name="max_df",
            field=models.FloatField(
                default=0.8,
                help_text="Se descartan los terminos presentes en una proporcion mayor de documentos (0-1)",
                verbose_name="Frecuencia Máxima de Documento",
            ),
        ),
        migrations.AddField(
            model_name="topicmodeling",
            name="max_features",
            field=models.PositiveIntegerField(
                default=2000,
                help_text="Numero maximo de terminos (los mas frecuentes) de la matriz documento-termino",
                verbose_name="Tamaño Máximo del Vocabulario",
            ),
        ),
        migrations.AddField(
            model_name="topicmodeling",
            name="min_df",
            field=models.PositiveIntegerField(
                default=2,
                help_text="Se descartan los terminos que aparecen en menos documentos que este valor",
                verbose_name="Frecuencia Mínima de Documento",
            ),
        ),
        migrations.AddField(
            model_name="topicmodeling",
            name="ngram_max",
            field=models.PositiveSmallIntegerField(
                default=2, verbose_name="N-grama Máximo"
            ),
        ),
        migrations.AddField(
            model_name="topicmodeling",
            name="ngram_min",
            field=models.PositiveSmallIntegerField(
                default=1, verbose_name="N-grama Mínimo"
            ),
        ),
    ]
