# Generated by Django 4.2.8 on 2026-01-04 12:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("data_preparation", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="BagOfWords",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Nombre descriptivo del análisis BoW", max_length=200
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Descripción opcional del análisis",
                        null=True,
                    ),
                ),
                (
                    "vectorization_method",
                    models.CharField(
                        choices=[
                            ("count", "Count Vectorizer (Frecuencias)"),
                            ("tfidf", "TF-IDF Vectorizer (Importancia)"),
                        ],
                        default="tfidf",
                        help_text="Método de vectorización a utilizar",
                        max_length=20,
                    ),
                ),
                (
                    "max_features",
                    models.IntegerField(
                        default=1000,
                        help_text="Número máximo de features (palabras) a considerar",
                    ),
                ),
                (
                    "min_df",
                    models.IntegerField(
                        default=1,
                        help_text="Mínima frecuencia de documento (ignorar términos que aparecen en menos de N documentos)",
                    ),
                ),
                (
                    "max_df",
                    models.FloatField(
                        default=1.0,
                        help_text="Máxima frecuencia de documento (ignorar términos que aparecen en más de % de documentos)",
                    ),
                ),
                (
                    "ngram_min",
                    models.IntegerField(
                        default=1, help_text="Tamaño mínimo de n-gramas (1 = unigramas)"
                    ),
                ),
                (
                    "ngram_max",
                    models.IntegerField(
                        default=1,
                        help_text="Tamaño máximo de n-gramas (1 = unigramas, 2 = bigramas, etc.)",
                    ),
                ),
                (
                    "use_idf",
                    models.BooleanField(
                        default=True, help_text="Usar IDF (solo para TF-IDF)"
                    ),
                ),
                (
                    "sublinear_tf",
                    models.BooleanField(
                        default=False,
                        help_text="Usar escala logarítmica para TF (solo para TF-IDF)",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pendiente"),
                            ("processing", "Procesando"),
                            ("completed", "Completado"),
                            ("error", "Error"),
                        ],
                        default="pending",
                        help_text="Estado actual del análisis",
                        max_length=20,
                    ),
                ),
                (
                    "current_stage",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("pending", "Pendiente"),
                            ("loading_data", "Cargando datos preprocesados"),
                            ("vectorizing", "Vectorizando documentos"),
                            ("calculating_stats", "Calculando estadísticas"),
                            ("saving_results", "Guardando resultados"),
                            ("completed", "Completado"),
                        ],
                        default="pending",
                        help_text="Etapa actual del procesamiento",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "progress_percentage",
                    models.IntegerField(
                        default=0, help_text="Porcentaje de progreso (0-100)"
                    ),
                ),
                (
                    "error_message",
                    models.TextField(
                        blank=True,
                        help_text="Mensaje de error si el procesamiento falla",
                        null=True,
                    ),
                ),
                (
                    "vocabulary_size",
                    models.IntegerField(
                        default=0, help_text="Tamaño del vocabulario generado"
                    ),
                ),
                (
                    "document_count",
                    models.IntegerField(
                        default=0, help_text="Número de documentos procesados"
                    ),
                ),
                (
                    "matrix_shape",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Dimensiones de la matriz documento-término (rows, cols)",
                    ),
                ),
                (
                    "matrix_sparsity",
                    models.FloatField(
                        default=0.0, help_text="Esparsidad de la matriz (% de ceros)"
                    ),
                ),
                (
                    "top_terms",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Top términos más frecuentes/importantes con sus valores",
                    ),
                ),
                (
                    "vocabulary",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Vocabulario completo (término: índice)",
                    ),
                ),
                (
                    "feature_names",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Lista de nombres de features (palabras)",
                    ),
                ),
                (
                    "avg_terms_per_document",
                    models.FloatField(
                        default=0.0,
                        help_text="Promedio de términos únicos por documento",
                    ),
                ),
                (
                    "total_term_occurrences",
                    models.IntegerField(
                        default=0,
                        help_text="Total de ocurrencias de términos en el corpus",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="Fecha de creación"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="Fecha de última actualización"
                    ),
                ),
                (
                    "processing_started_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Fecha de inicio del procesamiento",
                        null=True,
                    ),
                ),
                (
                    "processing_completed_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Fecha de finalización del procesamiento",
                        null=True,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        help_text="Usuario que creó este análisis",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bag_of_words_analyses",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "data_preparation",
                    models.ForeignKey(
                        help_text="Preparación de datos a utilizar",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bag_of_words_analyses",
                        to="data_preparation.datapreparation",
                    ),
                ),
            ],
            options={
                "verbose_name": "Bolsa de Palabras",
                "verbose_name_plural": "Bolsas de Palabras",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["created_by", "-created_at"],
                        name="bag_of_word_created_829cf3_idx",
                    ),
                    models.Index(
                        fields=["data_preparation"],
                        name="bag_of_word_data_pr_d0a3b8_idx",
                    ),
                    models.Index(
                        fields=["status"], name="bag_of_word_status_6c5f86_idx"
                    ),
                ],
            },
        ),
    ]
