# Generated by Django 4.2.8 on 2026-01-04 13:57

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("bag_of_words", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="bagofwords",
            name="sublinear_tf",
        ),
        migrations.RemoveField(
            model_name="bagofwords",
            name="use_idf",
        ),
        migrations.RemoveField(
            model_name="bagofwords",
            name="vectorization_method",
        ),
    ]
