# Generated by Django 6.0.3 on 2026-03-26 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bag_of_words', '0003_add_model_artifact'),
    ]

    operations = [
        migrations.AddField(
            model_name='bagofwords',
            name='model_artifact_bin',
            field=models.BinaryField(blank=True, help_text='Vectorizador serializado (joblib) almacenado en DB para persistencia en hosting efímero', null=True),
        ),
    ]
